spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update  # 自动修改映射字段
    show-sql: true   # sql语句输出在控制台
logging:
  level:
    root: info
    com.lyx: debug
  file: log/blog-dev.log
server:
  port: 8080